# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'introduce.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Introduce(object):
    def setupUi(self, Introduce):
        Introduce.setObjectName("Introduce")
        Introduce.resize(602, 686)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/:/Image/中南大学校徽.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Introduce.setWindowIcon(icon)
        self.gridLayout = QtWidgets.QGridLayout(Introduce)
        self.gridLayout.setObjectName("gridLayout")
        self.introduce = QtWidgets.QTextEdit(Introduce)
        self.introduce.setReadOnly(True)
        self.introduce.setObjectName("introduce")
        self.gridLayout.addWidget(self.introduce, 0, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.buttonOK = QtWidgets.QPushButton(Introduce)
        self.buttonOK.setStyleSheet("*{\n"
"    font-family:;\n"
"    font: 9pt \"华文宋体\";\n"
"    font-size:18px;\n"
"}\n"
"QPushButton:hover { \n"
"color: green;\n"
"font-size:22px;\n"
"border:1px solid #1d649c\n"
"}")
        self.buttonOK.setObjectName("buttonOK")
        self.horizontalLayout.addWidget(self.buttonOK)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.gridLayout.addLayout(self.horizontalLayout, 1, 0, 1, 1)

        self.retranslateUi(Introduce)
        QtCore.QMetaObject.connectSlotsByName(Introduce)

    def retranslateUi(self, Introduce):
        _translate = QtCore.QCoreApplication.translate
        Introduce.setWindowTitle(_translate("Introduce", "软件介绍"))
        self.buttonOK.setText(_translate("Introduce", "确定"))
