# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'LoginWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LoginWindow(object):
    def setupUi(self, LoginWindow):
        LoginWindow.setObjectName("LoginWindow")
        LoginWindow.resize(441, 370)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/:/Image/CSU2.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        LoginWindow.setWindowIcon(icon)
        LoginWindow.setStyleSheet("*{\n"
"    font-family:;\n"
"    font: 9pt \"华文宋体\";\n"
"    font-size:18px;\n"
"}\n"
"QPushButton:hover { \n"
"color: green;\n"
"font-size:22px;\n"
"border:1px solid #1d649c\n"
"}")
        self.verticalLayout = QtWidgets.QVBoxLayout(LoginWindow)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.labelIcon = QtWidgets.QLabel(LoginWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelIcon.sizePolicy().hasHeightForWidth())
        self.labelIcon.setSizePolicy(sizePolicy)
        self.labelIcon.setMaximumSize(QtCore.QSize(230, 200))
        self.labelIcon.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.labelIcon.setText("")
        self.labelIcon.setPixmap(QtGui.QPixmap(":/:/Image/CSU2.ico"))
        self.labelIcon.setScaledContents(True)
        self.labelIcon.setObjectName("labelIcon")
        self.horizontalLayout_3.addWidget(self.labelIcon)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setHorizontalSpacing(15)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(LoginWindow)
        self.label.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.userEdit = QtWidgets.QLineEdit(LoginWindow)
        self.userEdit.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.userEdit.setText("")
        self.userEdit.setObjectName("userEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.userEdit)
        self.label_2 = QtWidgets.QLabel(LoginWindow)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.pwdEdit = QtWidgets.QLineEdit(LoginWindow)
        self.pwdEdit.setText("")
        self.pwdEdit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.pwdEdit.setObjectName("pwdEdit")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.pwdEdit)
        self.verticalLayout.addLayout(self.formLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.checkRemember = QtWidgets.QCheckBox(LoginWindow)
        self.checkRemember.setObjectName("checkRemember")
        self.horizontalLayout_2.addWidget(self.checkRemember)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.buttonClear = QtWidgets.QPushButton(LoginWindow)
        self.buttonClear.setObjectName("buttonClear")
        self.horizontalLayout_2.addWidget(self.buttonClear)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.horizontalLayout_2.setStretch(0, 2)
        self.horizontalLayout_2.setStretch(1, 1)
        self.horizontalLayout_2.setStretch(2, 1)
        self.horizontalLayout_2.setStretch(3, 1)
        self.horizontalLayout_2.setStretch(4, 2)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.buttonLogin = QtWidgets.QPushButton(LoginWindow)
        self.buttonLogin.setObjectName("buttonLogin")
        self.horizontalLayout.addWidget(self.buttonLogin)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem4)
        self.buttonCancel = QtWidgets.QPushButton(LoginWindow)
        self.buttonCancel.setObjectName("buttonCancel")
        self.horizontalLayout.addWidget(self.buttonCancel)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem5)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(LoginWindow)
        self.buttonLogin.clicked.connect(LoginWindow.on_Login_Clicked)
        self.buttonCancel.clicked.connect(LoginWindow.on_Cancel_Clicked)
        self.userEdit.textChanged['QString'].connect(LoginWindow.on_userEdit_changed)
        QtCore.QMetaObject.connectSlotsByName(LoginWindow)

    def retranslateUi(self, LoginWindow):
        _translate = QtCore.QCoreApplication.translate
        LoginWindow.setWindowTitle(_translate("LoginWindow", "用户登录"))
        self.label.setText(_translate("LoginWindow", "用户名："))
        self.userEdit.setPlaceholderText(_translate("LoginWindow", "在此输入账号"))
        self.label_2.setText(_translate("LoginWindow", "密  码："))
        self.pwdEdit.setPlaceholderText(_translate("LoginWindow", "在此输入密码"))
        self.checkRemember.setText(_translate("LoginWindow", "记住密码"))
        self.buttonClear.setText(_translate("LoginWindow", "清空登录记录"))
        self.buttonLogin.setText(_translate("LoginWindow", "登录"))
        self.buttonCancel.setText(_translate("LoginWindow", "取消"))
